### ISSUE TITLE
About this example

### ISSUE THREAD

**Issue by mkuiwu** [SINTEF-9012/kafka-mqtt-source-connector#2]
Does this example require commercial components of EMQX？
Is the open source version enough?

**Comment by asmhug** [comment]
Hi!

This example is only performed using the non-commercial (read: free) version of EMQX.

We are currently working on creating a robust large-scale version of this, with clustered EMQX and Kafka. This too, only using the free version of EMQX.

Good luck!

/Åsmund

**Comment by mkuiwu** [comment]
I see. I'm very optimistic about you.
