### ISSUE TITLE
getting Started

### ISSUE THREAD

**Issue by mkuiwu** [SINTEF-9012/kafka-mqtt-source-connector#3]
1. I think in the step of creating topic 

   ```
   "path-to-kafka" /kafka_2.13-2.4.1/bin/kafka-topics
   ```

    should be changed to 

   ```
   "path-to-kafka" /kafka_2.13-2.4.1/ bin / kafka-topics.sh
   ```

    and the -p parameter can be added when creating the / usr / share / java / kafka directory

**Comment by asmhug** [comment]
That is correct. I have done this in different environments, and on different platforms. Running it on Linux should require a ".sh" suffic. Thank you so much for the feedback!
